from quool import Broker


class AShareBroker(Broker):
    """Broker specialization for China A-share market lot-size rules.

    AShareBroker enforces the A-share trading convention that order quantities
    must be in lots of 100 shares. Any requested quantity is floored to the
    nearest multiple of 100. If the floored quantity is less than or equal to
    zero, no order is created.

    This class delegates actual order creation and submission to the base Broker
    after applying the lot-size adjustment.
    """

    def create(
        self,
        type: str,
        code: str,
        quantity: int,
        exectype: str,
        limit: float = None,
        trigger: float = None,
        id: str = None,
        valid: str = None,
    ):
        """Create an order with quantity adjusted to A-share lot-size (100-share lots).

        The input quantity is floored to the nearest multiple of 100:
          adjusted_quantity = floor(quantity / 100) * 100

        If the adjusted quantity is greater than zero, the method delegates to
        the base Broker.create() and returns the created order; otherwise, it
        returns None without creating an order.

        Args:
          type (str): Order side, typically Order.BUY or Order.SELL.
          code (str): Instrument code (ticker).
          quantity (int): Requested quantity (will be floored to 100-share lots).
          exectype (str): Execution type (e.g., Order.MARKET, Order.LIMIT, Order.STOP, Order.STOPLIMIT).
          limit (float, optional): Limit price for LIMIT/STOPLIMIT orders. Defaults to None.
          trigger (float, optional): Trigger price for STOP/STOPLIMIT orders. Defaults to None.
          id (str, optional): Order identifier. Defaults to None (auto-generated by base Broker).
          valid (str, optional): Good-till timestamp as a pandas-parsable string. Defaults to None.

        Returns:
          Order or None: The created order if the adjusted quantity > 0; otherwise None.

        Raises:
          ValueError: If the base broker has no current time set or if its creation
            validation fails.
        """
        if type == self.order_type.BUY:
            quantity = int(quantity // 100 * 100)
        return super().create(
            type=type,
            code=code,
            quantity=quantity,
            exectype=exectype,
            limit=limit,
            trigger=trigger,
            id=id,
            valid=valid,
        )
